// src/components/importWizard/TemplateLibraryCard.jsx
//
// TEAM UX POLISH — one category card on the Template Library page. Pure presentation: every file it
// can produce is generated by the EXISTING template/practice generators (templateModel.js /
// xlsxTemplate.js / sampleWorkspace.js) — no new parser, no new template builder, no network call.
// A download here can never create a contact, start a campaign, or reach the backend.

import { useState } from "react";
import { templateHeaders, templateFileBase, templateCsv, isBusinessTemplateKind } from "../../import/templateModel.js";
import { templateXlsx, templatePracticeXlsx, practiceFileBase, XLSX_MIME } from "../../import/xlsxTemplate.js";
import { sampleContactsFor, sampleCsvFor } from "../../import/sampleWorkspace.js";

const PURPLE = "linear-gradient(135deg,#6d74ee,#764ba2)";
const card = { background: "#fff", border: "1px solid rgba(27,24,48,.1)", borderRadius: 14, padding: 18 };
const btn = (bg, fg = "#fff") => ({ background: bg, color: fg, border: bg === "transparent" ? "1px solid rgba(27,24,48,.15)" : "none", borderRadius: 11, padding: "8px 14px", fontWeight: 700, fontSize: ".78rem", cursor: "pointer" });

// Display copy only — matches the wording already shown on the wizard's own category-select screen
// (ContactImportWizard.jsx PERSONAL_GROUPS / BUSINESS_GROUPS). Not a data model; nothing here is
// consumed by import/commit logic.
const CARD_COPY = {
  family: { title: "Family", copy: "Parents, children, siblings, and extended family." },
  friend: { title: "Friends", copy: "Best friends, neighbors, teammates, and classmates." },
  professional: { title: "Professional", copy: "Colleagues, mentors, and work connections important to you." },
  employee: { title: "Employees", copy: "Employees, personnel, departments, and workplace contacts." },
  client: { title: "Clients", copy: "Clients, customers, companies, and important customer contacts." },
  vendor: { title: "Vendors", copy: "Vendors, suppliers, service providers, and business partners." },
};

// Medallion icon + gradient per category — visually unifies this card with the wizard's own
// category-select tiles. Icon markup and gradient values are copied from ContactImportWizard.jsx
// (HomeIcon/HeartIcon/BriefcaseIcon/PeopleIcon/HandshakeIcon/PackageIcon + .gmiw-medallion /
// --plum / --rose) so the two surfaces read as one system; purely presentational, no shared import.
const MEDALLION_GRADIENT = {
  default: "radial-gradient(circle at 32% 30%,#8a5fd0,#5b3a9e)",
  plum: "radial-gradient(circle at 32% 30%,#a552a3,#6d2d6d)",
  rose: "radial-gradient(circle at 32% 30%,#cf6aa2,#8e2f66)",
};
function HomeIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" role="img" aria-hidden="true">
      <path d="M3 11l9-7 9 7" /><path d="M5 10v9h14v-9" /><path d="M10 19v-5h4v5" />
    </svg>
  );
}
function HeartIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="#fff" role="img" aria-hidden="true">
      <path d="M12 21s-7.5-4.9-10-9.2C.4 8.7 1.9 5 5.3 5c2 0 3.4 1.2 4.2 2.4C10.3 6.2 11.7 5 13.7 5c3.4 0 4.9 3.7 3.3 6.8C19.5 16.1 12 21 12 21z" />
    </svg>
  );
}
function BriefcaseIcon() {
  return (
    <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" role="img" aria-hidden="true">
      <rect x="3" y="7.5" width="18" height="12" rx="2.2" />
      <path d="M9 7.5V6a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v1.5" />
      <path d="M3 12.5h18" />
    </svg>
  );
}
function PeopleIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" role="img" aria-hidden="true">
      <circle cx="9" cy="8" r="3" /><path d="M2.5 20a6.5 6.5 0 0 1 13 0" />
      <path d="M16 5.2a3 3 0 0 1 0 5.6" /><path d="M17.5 14.3A6.5 6.5 0 0 1 21.5 20" />
    </svg>
  );
}
function HandshakeIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" role="img" aria-hidden="true">
      <path d="M11 6.5 8.5 9a2 2 0 0 0 0 2.8l.2.2a2 2 0 0 0 2.8 0L13 10.5" />
      <path d="m13 10.5 2.5 2.5a2 2 0 0 1 0 2.8l-.2.2a2 2 0 0 1-2.8 0l-2-2" />
      <path d="M3 8.5 6.5 5H10l3 3" /><path d="M21 8.5 17.5 5H14" /><path d="M3 8.5v6M21 8.5v6" />
    </svg>
  );
}
function PackageIcon() {
  return (
    <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" role="img" aria-hidden="true">
      <path d="M21 8 12 3 3 8v8l9 5 9-5z" /><path d="M3 8l9 5 9-5" /><path d="M12 13v8" /><path d="M7.5 5.5 16.5 10.5" />
    </svg>
  );
}
const MEDALLION_META = {
  family: { Icon: HomeIcon, gradient: MEDALLION_GRADIENT.default },
  friend: { Icon: HeartIcon, gradient: MEDALLION_GRADIENT.rose },
  professional: { Icon: BriefcaseIcon, gradient: MEDALLION_GRADIENT.plum },
  employee: { Icon: PeopleIcon, gradient: MEDALLION_GRADIENT.default },
  client: { Icon: HandshakeIcon, gradient: MEDALLION_GRADIENT.rose },
  vendor: { Icon: PackageIcon, gradient: MEDALLION_GRADIENT.plum },
};
const medallionStyle = (gradient) => ({
  width: 40, height: 40, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center",
  background: gradient, boxShadow: "0 8px 16px -8px rgba(70,30,120,.7)", flexShrink: 0,
});

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
}

export default function TemplateLibraryCard({ kind }) {
  const [busy, setBusy] = useState(false);
  const copy = CARD_COPY[kind];
  const business = isBusinessTemplateKind(kind);
  const headers = templateHeaders(kind);
  const medallion = MEDALLION_META[kind];
  const MedallionIcon = medallion.Icon;

  const downloadBlankExcel = () => {
    setBusy(true);
    try {
      const base = templateFileBase(kind);
      triggerDownload(new Blob([templateXlsx(kind, { generatedUtc: new Date().toISOString().slice(0, 10) })], { type: XLSX_MIME }), `${base}.xlsx`);
    } finally { setBusy(false); }
  };
  const downloadBlankCsv = () => {
    setBusy(true);
    try {
      triggerDownload(new Blob([templateCsv(kind)], { type: "text/csv;charset=utf-8" }), `${templateFileBase(kind)}.csv`);
    } finally { setBusy(false); }
  };
  const downloadPracticeExcel = () => {
    setBusy(true);
    try {
      const contacts = sampleContactsFor(kind);
      triggerDownload(new Blob([templatePracticeXlsx(kind, { contacts, generatedUtc: new Date().toISOString().slice(0, 10) })], { type: XLSX_MIME }), `${practiceFileBase(kind)}.xlsx`);
    } finally { setBusy(false); }
  };
  const downloadPracticeCsv = () => {
    setBusy(true);
    try {
      triggerDownload(new Blob([sampleCsvFor(kind)], { type: "text/csv;charset=utf-8" }), `greetme-practice-${kind}.csv`);
    } finally { setBusy(false); }
  };

  return (
    <div data-testid={`template-library-card-${kind}`} style={{ ...card, display: "flex", flexDirection: "column" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        <span style={medallionStyle(medallion.gradient)} aria-hidden="true"><MedallionIcon /></span>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <h3 style={{ margin: 0, fontFamily: "Georgia,serif" }}>{copy.title}</h3>
          <span style={{ fontSize: ".68rem", fontWeight: 700, letterSpacing: ".04em", textTransform: "uppercase", color: "#6d74ee" }}>
            {business ? "Business" : "Personal"}
          </span>
        </div>
      </div>
      <p style={{ color: "#5b5570", fontSize: ".85rem", margin: "6px 0 10px" }}>{copy.copy}</p>

      <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 12 }}>
        {headers.map((h) => (
          <span key={h} style={{ fontSize: ".68rem", padding: "2px 8px", borderRadius: 999, background: "#f4f2fb", color: "#5b5570", border: "1px solid rgba(27,24,48,.08)" }}>
            {h}
          </span>
        ))}
      </div>

      <div style={{ marginTop: "auto" }}>
        <p style={{ fontSize: ".76rem", fontWeight: 700, margin: "0 0 6px", color: "#1b1830" }}>Blank template — no contacts included</p>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 12 }}>
          <button type="button" data-testid={`tpl-lib-excel-${kind}`} style={btn(PURPLE)} disabled={busy} onClick={downloadBlankExcel}>
            Guided Excel Template
          </button>
          <button type="button" data-testid={`tpl-lib-csv-${kind}`} style={btn("transparent", "#1b1830")} disabled={busy} onClick={downloadBlankCsv}>
            Basic CSV Template
          </button>
        </div>

        <p style={{ fontSize: ".76rem", fontWeight: 700, margin: "0 0 6px", color: "#1b1830" }}>
          Practice sample <span style={{ fontWeight: 400, color: "#5b5570" }}>— fictional contacts, nothing is saved</span>
        </p>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          <button type="button" data-testid={`tpl-lib-practice-excel-${kind}`} style={btn(PURPLE)} disabled={busy} onClick={downloadPracticeExcel}>
            Practice Excel Workbook
          </button>
          <button type="button" data-testid={`tpl-lib-practice-csv-${kind}`} style={btn("transparent", "#1b1830")} disabled={busy} onClick={downloadPracticeCsv}>
            Practice CSV
          </button>
        </div>
      </div>
    </div>
  );
}
