// src/components/importWizard/TemplateLibraryCard.jsx
//
// TEAM UX POLISH — one category card on the Template Library page. Pure presentation: every file it
// can produce is generated by the EXISTING template/practice generators (templateModel.js /
// xlsxTemplate.js / sampleWorkspace.js) — no new parser, no new template builder, no network call.
// A download here can never create a contact, start a campaign, or reach the backend.

import { useState } from "react";
import { templateHeaders, templateFileBase, templateCsv, isBusinessTemplateKind } from "../../import/templateModel.js";
import { templateXlsx, templatePracticeXlsx, practiceFileBase, XLSX_MIME } from "../../import/xlsxTemplate.js";
import { sampleContactsFor, sampleCsvFor } from "../../import/sampleWorkspace.js";

const PURPLE = "linear-gradient(135deg,#6d74ee,#764ba2)";
const card = { background: "#fff", border: "1px solid rgba(27,24,48,.1)", borderRadius: 14, padding: 18 };
const btn = (bg, fg = "#fff") => ({ background: bg, color: fg, border: bg === "transparent" ? "1px solid rgba(27,24,48,.15)" : "none", borderRadius: 11, padding: "8px 14px", fontWeight: 700, fontSize: ".78rem", cursor: "pointer" });

// Display copy only — matches the wording already shown on the wizard's own category-select screen
// (ContactImportWizard.jsx PERSONAL_GROUPS / BUSINESS_GROUPS). Not a data model; nothing here is
// consumed by import/commit logic.
const CARD_COPY = {
  family: { title: "Family", copy: "Parents, children, siblings, and extended family." },
  friend: { title: "Friends", copy: "Best friends, neighbors, teammates, and classmates." },
  professional: { title: "Professional", copy: "Colleagues, mentors, and work connections important to you." },
  employee: { title: "Employees", copy: "Employees, personnel, departments, and workplace contacts." },
  client: { title: "Clients", copy: "Clients, customers, companies, and important customer contacts." },
  vendor: { title: "Vendors", copy: "Vendors, suppliers, service providers, and business partners." },
};

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
}

export default function TemplateLibraryCard({ kind }) {
  const [busy, setBusy] = useState(false);
  const copy = CARD_COPY[kind];
  const business = isBusinessTemplateKind(kind);
  const headers = templateHeaders(kind);

  const downloadBlankExcel = () => {
    setBusy(true);
    try {
      const base = templateFileBase(kind);
      triggerDownload(new Blob([templateXlsx(kind, { generatedUtc: new Date().toISOString().slice(0, 10) })], { type: XLSX_MIME }), `${base}.xlsx`);
    } finally { setBusy(false); }
  };
  const downloadBlankCsv = () => {
    setBusy(true);
    try {
      triggerDownload(new Blob([templateCsv(kind)], { type: "text/csv;charset=utf-8" }), `${templateFileBase(kind)}.csv`);
    } finally { setBusy(false); }
  };
  const downloadPracticeExcel = () => {
    setBusy(true);
    try {
      const contacts = sampleContactsFor(kind);
      triggerDownload(new Blob([templatePracticeXlsx(kind, { contacts, generatedUtc: new Date().toISOString().slice(0, 10) })], { type: XLSX_MIME }), `${practiceFileBase(kind)}.xlsx`);
    } finally { setBusy(false); }
  };
  const downloadPracticeCsv = () => {
    setBusy(true);
    try {
      triggerDownload(new Blob([sampleCsvFor(kind)], { type: "text/csv;charset=utf-8" }), `greetme-practice-${kind}.csv`);
    } finally { setBusy(false); }
  };

  return (
    <div data-testid={`template-library-card-${kind}`} style={{ ...card, display: "flex", flexDirection: "column" }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" }}>
        <h3 style={{ margin: 0, fontFamily: "Georgia,serif" }}>{copy.title}</h3>
        <span style={{ fontSize: ".68rem", fontWeight: 700, letterSpacing: ".04em", textTransform: "uppercase", color: "#6d74ee" }}>
          {business ? "Business" : "Personal"}
        </span>
      </div>
      <p style={{ color: "#5b5570", fontSize: ".85rem", margin: "6px 0 10px" }}>{copy.copy}</p>

      <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 12 }}>
        {headers.map((h) => (
          <span key={h} style={{ fontSize: ".68rem", padding: "2px 8px", borderRadius: 999, background: "#f4f2fb", color: "#5b5570", border: "1px solid rgba(27,24,48,.08)" }}>
            {h}
          </span>
        ))}
      </div>

      <div style={{ marginTop: "auto" }}>
        <p style={{ fontSize: ".76rem", fontWeight: 700, margin: "0 0 6px", color: "#1b1830" }}>Blank template — no contacts included</p>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 12 }}>
          <button type="button" data-testid={`tpl-lib-excel-${kind}`} style={btn(PURPLE)} disabled={busy} onClick={downloadBlankExcel}>
            Guided Excel Template
          </button>
          <button type="button" data-testid={`tpl-lib-csv-${kind}`} style={btn("transparent", "#1b1830")} disabled={busy} onClick={downloadBlankCsv}>
            Basic CSV Template
          </button>
        </div>

        <p style={{ fontSize: ".76rem", fontWeight: 700, margin: "0 0 6px", color: "#1b1830" }}>
          Practice sample <span style={{ fontWeight: 400, color: "#5b5570" }}>— fictional contacts, nothing is saved</span>
        </p>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          <button type="button" data-testid={`tpl-lib-practice-excel-${kind}`} style={btn(PURPLE)} disabled={busy} onClick={downloadPracticeExcel}>
            Practice Excel Workbook
          </button>
          <button type="button" data-testid={`tpl-lib-practice-csv-${kind}`} style={btn("transparent", "#1b1830")} disabled={busy} onClick={downloadPracticeCsv}>
            Practice CSV
          </button>
        </div>
      </div>
    </div>
  );
}
